# Site
name: "MyCompany Model Cards"
title: "MyCompany Model Cards"
description: "Model cards provide information about the performance, limitations, and ethical considerations of a machine learning model, and are used to help a wide range of audiences understand and properly use the models."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/modelcard'
url: ''
google_analytics: ''
disqus: 'demowebsite'
include: ["_pages"]

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    email: sal@mycompany.com
    description: "ML engineer at MyCompany."
  john:
    name: John
    display_name: John    
    email: john@mycompany.com
    description: "Applied Research Scientist at MyCompany."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
